### ISSUE TITLE
Fork or copy

### ISSUE THREAD

**Issue by royfocker19** [AchimPieters/esp32-homekit-camera#2]
Hi, quick question, is this a fork of @maximkulkin, a copy from scratch or something different? I can’t see the code but I can see you ask for donation in this specific accessory, which makes me think it should be something different.
Regards

**Comment by AchimPieters** [comment]
@royfocker19 this is a workout of  @maximkulkin his git. it's all described on my blog or has the be release on my blog. And yes, @maximkulkin knows about it, and is fine with it.
regards
