### ISSUE TITLE
Flashing main.bin

### ISSUE THREAD

**Issue by leonrrafael** [AchimPieters/esp32-homekit-camera#3]
Hello there!

Im using your binary file to flash a ESP CAM but its not working.... all i got is a flashing led and no boot.

Is there anything missing to me?

Tks!

**Comment by AchimPieters** [comment]
@leonrrafael I'm currently building a whole new repository, build on the newest IDF and other needed software. You can find it here: https://github.com/AchimPieters/esp32-homekit-demo. It is still in construction, but will soon be completed, and then the ESP Camera is on my list.
