### ISSUE TITLE
Multiple Type errors

### ISSUE THREAD

**Issue by Jimmy106-e** [AchimPieters/esp32-homekit-camera#5]
There are multiple Type errors while compiling and flashing. Any idea how to fix?

**Comment by AchimPieters** [comment]
@Jimmy106-e I'm currently building a whole new repository, build on the newest IDF and other needed software. You cna find it here: https://github.com/AchimPieters/esp32-homekit-demo. It is still in construction, but will soon be completed and then the ESP Camera is on my list.
